//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.123
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Единицы измер.
    /// </summary>
    // *** Start programmer edit section *** (ЕдиницыИзмер CustomAttributes)

    // *** End programmer edit section *** (ЕдиницыИзмер CustomAttributes)
    [AutoAltered()]
    [Caption("Единицы измер")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЕдиницыИзмерE", new string[] {
            "ЕдиницаИзмер as \'Единица измер\'"})]
    [View("ЕдиницыИзмерL", new string[] {
            "ЕдиницаИзмер as \'Единица измер\'"})]
    public class ЕдиницыИзмер : ICSSoft.STORMNET.DataObject
    {
        
        private string fЕдиницаИзмер;
        
        // *** Start programmer edit section *** (ЕдиницыИзмер CustomMembers)

        // *** End programmer edit section *** (ЕдиницыИзмер CustomMembers)

        
        /// <summary>
        /// ЕдиницаИзмер.
        /// </summary>
        // *** Start programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер CustomAttributes)

        // *** End programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер CustomAttributes)
        [StrLen(255)]
        public virtual string ЕдиницаИзмер
        {
            get
            {
                // *** Start programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер Get start)

                // *** End programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер Get start)
                string result = this.fЕдиницаИзмер;
                // *** Start programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер Get end)

                // *** End programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер Set start)

                // *** End programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер Set start)
                this.fЕдиницаИзмер = value;
                // *** Start programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер Set end)

                // *** End programmer edit section *** (ЕдиницыИзмер.ЕдиницаИзмер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЕдиницыИзмерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЕдиницыИзмерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЕдиницыИзмерE", typeof(IIS.123.ЕдиницыИзмер));
                }
            }
            
            /// <summary>
            /// "ЕдиницыИзмерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЕдиницыИзмерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЕдиницыИзмерL", typeof(IIS.123.ЕдиницыИзмер));
                }
            }
        }
    }
}
