//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.123
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ пост.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказПост CustomAttributes)

    // *** End programmer edit section *** (ЗаказПост CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ пост")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказПостE", new string[] {
            "Номер as \'Номер\'",
            "СостояниеОплаты as \'Состояние оплаты\'",
            "СуммаВклНДС as \'Сумма вкл НДС\'",
            "СуммаДокумента as \'Сумма документа\'",
            "СостОтгрузки as \'Сост отгрузки\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Контрагенты as \'Контрагенты\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "Организации as \'Организации\'",
            "Организации.Организация as \'Организация\'",
            "Склады as \'Склады\'",
            "Склады.Склад as \'Склад\'"}, Hidden=new string[] {
            "Контрагенты.Контрагент",
            "Организации.Организация",
            "Склады.Склад"})]
    [AssociatedDetailViewAttribute("ЗаказПостE", "ТЧЗаказ", "ТЧЗаказE", true, "", "Т ч заказ", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказПостE", "Контрагенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [MasterViewDefineAttribute("ЗаказПостE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Организация")]
    [MasterViewDefineAttribute("ЗаказПостE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [View("ЗаказПостL", new string[] {
            "Номер as \'Номер\'",
            "СостояниеОплаты as \'Состояние оплаты\'",
            "СуммаВклНДС as \'Сумма вкл НДС\'",
            "СуммаДокумента as \'Сумма документа\'",
            "СостОтгрузки as \'Сост отгрузки\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "Организации.Организация as \'Организация\'",
            "Склады.Склад as \'Склад\'"})]
    public class ЗаказПост : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.123.СостОплаты fСостояниеОплаты;
        
        private bool fСуммаВклНДС;
        
        private int fСуммаДокумента;
        
        private IIS.123.СостОтгрузки fСостОтгрузки;
        
        private System.DateTime fДатаНачала = System.DateTime.Now;
        
        private System.DateTime fДатаОкончания;
        
        private IIS.123.Контрагенты fКонтрагенты;
        
        private IIS.123.Организации fОрганизации;
        
        private IIS.123.Склады fСклады;
        
        private IIS.123.DetailArrayOfТЧЗаказ fТЧЗаказ;
        
        // *** Start programmer edit section *** (ЗаказПост CustomMembers)

        // *** End programmer edit section *** (ЗаказПост CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.ДатаНачала Get start)

                // *** End programmer edit section *** (ЗаказПост.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ЗаказПост.ДатаНачала Get end)

                // *** End programmer edit section *** (ЗаказПост.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.ДатаНачала Set start)

                // *** End programmer edit section *** (ЗаказПост.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ЗаказПост.ДатаНачала Set end)

                // *** End programmer edit section *** (ЗаказПост.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.ДатаОкончания Get start)

                // *** End programmer edit section *** (ЗаказПост.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ЗаказПост.ДатаОкончания Get end)

                // *** End programmer edit section *** (ЗаказПост.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.ДатаОкончания Set start)

                // *** End programmer edit section *** (ЗаказПост.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ЗаказПост.ДатаОкончания Set end)

                // *** End programmer edit section *** (ЗаказПост.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.Номер CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.Номер Get start)

                // *** End programmer edit section *** (ЗаказПост.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ЗаказПост.Номер Get end)

                // *** End programmer edit section *** (ЗаказПост.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.Номер Set start)

                // *** End programmer edit section *** (ЗаказПост.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ЗаказПост.Номер Set end)

                // *** End programmer edit section *** (ЗаказПост.Номер Set end)
            }
        }
        
        /// <summary>
        /// СостОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.СостОтгрузки CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.СостОтгрузки CustomAttributes)
        public virtual IIS.123.СостОтгрузки СостОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.СостОтгрузки Get start)

                // *** End programmer edit section *** (ЗаказПост.СостОтгрузки Get start)
                IIS.123.СостОтгрузки result = this.fСостОтгрузки;
                // *** Start programmer edit section *** (ЗаказПост.СостОтгрузки Get end)

                // *** End programmer edit section *** (ЗаказПост.СостОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.СостОтгрузки Set start)

                // *** End programmer edit section *** (ЗаказПост.СостОтгрузки Set start)
                this.fСостОтгрузки = value;
                // *** Start programmer edit section *** (ЗаказПост.СостОтгрузки Set end)

                // *** End programmer edit section *** (ЗаказПост.СостОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// СостояниеОплаты.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.СостояниеОплаты CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.СостояниеОплаты CustomAttributes)
        public virtual IIS.123.СостОплаты СостояниеОплаты
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.СостояниеОплаты Get start)

                // *** End programmer edit section *** (ЗаказПост.СостояниеОплаты Get start)
                IIS.123.СостОплаты result = this.fСостояниеОплаты;
                // *** Start programmer edit section *** (ЗаказПост.СостояниеОплаты Get end)

                // *** End programmer edit section *** (ЗаказПост.СостояниеОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.СостояниеОплаты Set start)

                // *** End programmer edit section *** (ЗаказПост.СостояниеОплаты Set start)
                this.fСостояниеОплаты = value;
                // *** Start programmer edit section *** (ЗаказПост.СостояниеОплаты Set end)

                // *** End programmer edit section *** (ЗаказПост.СостояниеОплаты Set end)
            }
        }
        
        /// <summary>
        /// СуммаВклНДС.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.СуммаВклНДС CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.СуммаВклНДС CustomAttributes)
        public virtual bool СуммаВклНДС
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.СуммаВклНДС Get start)

                // *** End programmer edit section *** (ЗаказПост.СуммаВклНДС Get start)
                bool result = this.fСуммаВклНДС;
                // *** Start programmer edit section *** (ЗаказПост.СуммаВклНДС Get end)

                // *** End programmer edit section *** (ЗаказПост.СуммаВклНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.СуммаВклНДС Set start)

                // *** End programmer edit section *** (ЗаказПост.СуммаВклНДС Set start)
                this.fСуммаВклНДС = value;
                // *** Start programmer edit section *** (ЗаказПост.СуммаВклНДС Set end)

                // *** End programmer edit section *** (ЗаказПост.СуммаВклНДС Set end)
            }
        }
        
        /// <summary>
        /// СуммаДокумента.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.СуммаДокумента CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.СуммаДокумента CustomAttributes)
        public virtual int СуммаДокумента
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.СуммаДокумента Get start)

                // *** End programmer edit section *** (ЗаказПост.СуммаДокумента Get start)
                int result = this.fСуммаДокумента;
                // *** Start programmer edit section *** (ЗаказПост.СуммаДокумента Get end)

                // *** End programmer edit section *** (ЗаказПост.СуммаДокумента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.СуммаДокумента Set start)

                // *** End programmer edit section *** (ЗаказПост.СуммаДокумента Set start)
                this.fСуммаДокумента = value;
                // *** Start programmer edit section *** (ЗаказПост.СуммаДокумента Set end)

                // *** End programmer edit section *** (ЗаказПост.СуммаДокумента Set end)
            }
        }
        
        /// <summary>
        /// Заказ пост.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.Контрагенты CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.Контрагенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагенты"})]
        [NotNull()]
        public virtual IIS.123.Контрагенты Контрагенты
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.Контрагенты Get start)

                // *** End programmer edit section *** (ЗаказПост.Контрагенты Get start)
                IIS.123.Контрагенты result = this.fКонтрагенты;
                // *** Start programmer edit section *** (ЗаказПост.Контрагенты Get end)

                // *** End programmer edit section *** (ЗаказПост.Контрагенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.Контрагенты Set start)

                // *** End programmer edit section *** (ЗаказПост.Контрагенты Set start)
                this.fКонтрагенты = value;
                // *** Start programmer edit section *** (ЗаказПост.Контрагенты Set end)

                // *** End programmer edit section *** (ЗаказПост.Контрагенты Set end)
            }
        }
        
        /// <summary>
        /// Заказ пост.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.Организации CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.Организации CustomAttributes)
        [PropertyStorage(new string[] {
                "Организации"})]
        [NotNull()]
        public virtual IIS.123.Организации Организации
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.Организации Get start)

                // *** End programmer edit section *** (ЗаказПост.Организации Get start)
                IIS.123.Организации result = this.fОрганизации;
                // *** Start programmer edit section *** (ЗаказПост.Организации Get end)

                // *** End programmer edit section *** (ЗаказПост.Организации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.Организации Set start)

                // *** End programmer edit section *** (ЗаказПост.Организации Set start)
                this.fОрганизации = value;
                // *** Start programmer edit section *** (ЗаказПост.Организации Set end)

                // *** End programmer edit section *** (ЗаказПост.Организации Set end)
            }
        }
        
        /// <summary>
        /// Заказ пост.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.Склады CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.Склады CustomAttributes)
        [PropertyStorage(new string[] {
                "Склады"})]
        [NotNull()]
        public virtual IIS.123.Склады Склады
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.Склады Get start)

                // *** End programmer edit section *** (ЗаказПост.Склады Get start)
                IIS.123.Склады result = this.fСклады;
                // *** Start programmer edit section *** (ЗаказПост.Склады Get end)

                // *** End programmer edit section *** (ЗаказПост.Склады Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.Склады Set start)

                // *** End programmer edit section *** (ЗаказПост.Склады Set start)
                this.fСклады = value;
                // *** Start programmer edit section *** (ЗаказПост.Склады Set end)

                // *** End programmer edit section *** (ЗаказПост.Склады Set end)
            }
        }
        
        /// <summary>
        /// Заказ пост.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПост.ТЧЗаказ CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.ТЧЗаказ CustomAttributes)
        public virtual IIS.123.DetailArrayOfТЧЗаказ ТЧЗаказ
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПост.ТЧЗаказ Get start)

                // *** End programmer edit section *** (ЗаказПост.ТЧЗаказ Get start)
                if ((this.fТЧЗаказ == null))
                {
                    this.fТЧЗаказ = new IIS.123.DetailArrayOfТЧЗаказ(this);
                }
                IIS.123.DetailArrayOfТЧЗаказ result = this.fТЧЗаказ;
                // *** Start programmer edit section *** (ЗаказПост.ТЧЗаказ Get end)

                // *** End programmer edit section *** (ЗаказПост.ТЧЗаказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПост.ТЧЗаказ Set start)

                // *** End programmer edit section *** (ЗаказПост.ТЧЗаказ Set start)
                this.fТЧЗаказ = value;
                // *** Start programmer edit section *** (ЗаказПост.ТЧЗаказ Set end)

                // *** End programmer edit section *** (ЗаказПост.ТЧЗаказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказПостE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказПостE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказПостE", typeof(IIS.123.ЗаказПост));
                }
            }
            
            /// <summary>
            /// "ЗаказПостL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказПостL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказПостL", typeof(IIS.123.ЗаказПост));
                }
            }
        }
    }
}
