//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.123
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сост отгрузки.
    /// </summary>
    // *** Start programmer edit section *** (СостОтгрузки CustomAttributes)

    // *** End programmer edit section *** (СостОтгрузки CustomAttributes)
    public enum СостОтгрузки
    {
        
        // *** Start programmer edit section *** (СостОтгрузки.НеОтгружен CustomAttributes)

        // *** End programmer edit section *** (СостОтгрузки.НеОтгружен CustomAttributes)
        [Caption("Не отгружен")]
        НеОтгружен,
        
        // *** Start programmer edit section *** (СостОтгрузки.ЧастичноОтгружен CustomAttributes)

        // *** End programmer edit section *** (СостОтгрузки.ЧастичноОтгружен CustomAttributes)
        [Caption("Частично отгружен")]
        ЧастичноОтгружен,
        
        // *** Start programmer edit section *** (СостОтгрузки.ПолностьюОтгружен CustomAttributes)

        // *** End programmer edit section *** (СостОтгрузки.ПолностьюОтгружен CustomAttributes)
        [Caption("Полностью отгружен")]
        ПолностьюОтгружен,
    }
}
